// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAtMxRw4dZ2JdvuUZc_PjJSkwD2ksTfag',
    appId: '1:19864941021:web:914b90e7c3368a8efe0634',
    messagingSenderId: '19864941021',
    projectId: 'mobile-advertising-f28e7',
    authDomain: 'mobile-advertising-f28e7.firebaseapp.com',
    databaseURL: 'https://mobile-advertising-f28e7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-advertising-f28e7.appspot.com',
    measurementId: 'G-HW8R08N1H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzTSFsZDIt9EAK3U3Al7F4cfSdEcEUpm0',
    appId: '1:19864941021:android:3552a7b63543cc60fe0634',
    messagingSenderId: '19864941021',
    projectId: 'mobile-advertising-f28e7',
    databaseURL: 'https://mobile-advertising-f28e7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-advertising-f28e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATy-SKZIn_2y4DHLmJFFZzklJ0mXoJ8So',
    appId: '1:19864941021:ios:c3f32d398c6ed3c7fe0634',
    messagingSenderId: '19864941021',
    projectId: 'mobile-advertising-f28e7',
    databaseURL: 'https://mobile-advertising-f28e7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-advertising-f28e7.appspot.com',
    iosBundleId: 'com.example.pbl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATy-SKZIn_2y4DHLmJFFZzklJ0mXoJ8So',
    appId: '1:19864941021:ios:2a49edc01eacb6acfe0634',
    messagingSenderId: '19864941021',
    projectId: 'mobile-advertising-f28e7',
    databaseURL: 'https://mobile-advertising-f28e7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-advertising-f28e7.appspot.com',
    iosBundleId: 'com.example.pbl.RunnerTests',
  );
}
